### ISSUE TITLE
Getting a 405 Method Not Allowed response

### ISSUE THREAD

**Issue by phil-warner** [DatatracCorporation/restify-cors-middleware2#18]
I've configured the package as follows but can't seem to get past a 405 response, after much experimentation and logging. What am I doing wrong?

```
const corsMiddleware = require('restify-cors-middleware2');
...
const cors = corsMiddleware({
  origins: ['*'],
  allowHeaders: ['*'],
  exposeHeaders: ['*'],
  credentials: true,
  allowCredentialsAllOrigins: true
});
app.pre(cors.preflight);
app.use(cors.actual);
```

**Comment by JimPatterson** [comment]
Can you provide some more detail about the requests?  The request and response headers behind the "OPTIONS" request and the failing request would be quite helpful.  Just make sure to remove any sensitive data (like authorization headers or sensitive bodies).

In case you don't know how to get the detail, the inspect tools in modern browsers have a network tab that records the requests made by the browser.

One of the key things here would be, is it the browser blocking based on CORS, or is it the server itself rejecting request for normal reasons (typo in the URL, unsupported request, etc).

**Comment by phil-warner** [comment]
Hi Jim. Thanks for the reply.

Here's an export of the OPTIONS request from Postman:

```
OPTIONS /v1/message/send HTTP/1.1
Content-Type: application/json
Authorization: JWT redacted
User-Agent: PostmanRuntime/7.26.10
Accept: */*
Postman-Token: 5cbb9088-abfd-468e-84b9-bff0504254fa
Host: qa.mydomain.co.uk
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 123
Cookie: __cfduid=dec315976135185fbcc12069a7cc3d4741616079421
{
"sender": "SenderID",
"destination": "07777777777",
"content": "My message",
"tag": ""
}
HTTP/1.1 405 Method Not Allowed
Date: Sat, 20 Mar 2021 18:20:42 GMT
Content-Type: application/json
Content-Length: 18
Connection: keep-alive
vary: origin,access-control-request-method,access-control-request-headers
CF-Cache-Status: DYNAMIC
cf-request-id: 08f2774baa0000541c461fa000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=gL8CaCdTCgwiirQhbknxrSox%2FkVefRcWBNh8s9WT3QrEKPJU9hrdJSNmZdB3IMp1Wb%2Fgi0TY9tzddLamtN18v2JbQg0C%2BBQZ1PiEhLukKShaIMcq9A%3D%3D"}],"max_age":604800}
NEL: {"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 6330f4bf7979541c-LHR
{"statusCode":405}
```

I can log activity from this library when the response is made, so it's definitely getting to the server.

Hope this helps.

**Comment by JimPatterson** [comment]
Phil,

I don't think you can test OPTIONS requests using postman.  See https://stackoverflow.com/questions/34931193/cors-faking-a-cors-preflight-from-postman-fails-to-return-headers for some discussion on the topic.

The reason I think this is that the request you gave above does not look like a valid OPTIONS request.  See https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS, but in specific, OPTIONS requests are not allowed to have bodies.

You can try the curl command from the mozilla link to verify that the CORS middleware is present by examining the `allow` header that is returned:

`curl -X OPTIONS -i <your-site>/v1/message/send`

**Comment by phil-warner** [comment]
Hi

This is what I get from a a curl -X OPTIONS call

```
Date: Sun, 21 Mar 2021 10:37:34 GMT
Content-Type: application/json
Content-Length: 18
Connection: keep-alive
Set-Cookie: __cfduid=d8d912f2717c79768663b95c8589f2b971616323054; expires=Tue, 20-Apr-21 10:37:34 GMT; path=/; domain=.thesmsworks.co.uk; HttpOnly; SameSite=Lax
vary: origin,access-control-request-method,access-control-request-headers
CF-Cache-Status: DYNAMIC
cf-request-id: 08f5f5a3f20000e6b478388000000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Report-To: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=3vMQoGgZ3Ss2h31cWpb9JCIzOApMDPAKV1zi1XMSUNwZhILowwtrMm%2FrHWb7emvuNcirsmQ6rrIvIHtUe9DRiNpUwUnYvTvZVcVconth5fYG24uZjQ%3D%3D"}],"max_age":604800}
NEL: {"max_age":604800,"report_to":"cf-nel"}
Server: cloudflare
CF-RAY: 63368bb3193ee6b4-EWR
```

I'm upgrading Restify from  v6 to v8, and using this for compatibility. The site has been serving this end-point on the prior configuration for several years.

Thanks for your help here.

**Comment by JimPatterson** [comment]
Phil,

I'm not sure what is happening here, can you isolate it into a small reproducer that can be shared?

**Comment by phil-warner** [comment]
Sure. What form would that take? Just a URL? I can DM that, if you like.

**Comment by JimPatterson** [comment]
I was thinking source code, maybe a gist here on github with sample code that is failing.  The versions you are using for all the stuff in that gist would be needed also.

**Comment by JimPatterson** [comment]
Did you also upgrade or change swagger-node-runner?  It looks like it has it's own CORS implementation build around the `cors` package, so my guess is that you are getting a conflict in the processing of CORS requests.  But I can't directly verify that since I don't enough of your code to actually run it and don't use swagger-node-runner personally.

I don't know if it will help, but https://github.com/swagger-api/swagger-node/issues/563 might help point you in the right direction.

I tried a simple reproducer based on our readme and it seemed to work just fine, as is our usage of restify-cors-middleware2 in production.  To help much more, I would need a simplified runnable version of your code that shows the problem.

Since you have a runnable version, one thing you could try would be the example shown at the end of https://stackoverflow.com/questions/24962005/how-to-get-list-of-all-routes-i-am-using-in-restify-server for how to see the routes and see if you can tell what code is handling OPTIONS requests.

**Comment by phil-warner** [comment]
Thanks Jim.

I think we're going re-consider how we implement Swagger and then take the best approach, rather than get into an ever-more convoluted version of our own implementation. Thanks for your thoughtful help here.
