### ISSUE TITLE
Cors headers not set.

### ISSUE THREAD

**Issue by prachikhadke** [DatatracCorporation/restify-cors-middleware2#20]
I used the following:

```
    const app = restify.createServer({
      name: 'Test Service'
    });
    const cors = corsMiddleware({
      origins: [ '*' ],
      allowHeaders: [ 'Authorization' ],
      exposeHeaders: [ 'Authorization' ]
    });
    app.pre(cors.preflight);
    app.use(cors.actual);
```

Import statements:
```
const restify = require('restify');
const corsMiddleware = require('restify-cors-middleware2');
```

Package dependencies:
```
    "restify": "^8.5.1",
    "restify-cors-middleware2": "^2.0.0",
```

I was expecting the cors header to be set in http requests. But it wasn't. What's missing?

**Comment by daniel-codrea-p4b** [comment]
I do have the same issue with the `Authorization` header.

**Comment by JimPatterson** [comment]
The plugin works fine for me in production, so there must be some other difference.  So lets see if we can find it.

1. Does your request have an origin header?
2. Are you using any other plugins?
3. Can you make a gist that reproduces the problem with a small code base?
